server:
   port: 8888

logging:
    path: E:/logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://124.222.243.64:3306/litemall
       username: root
       password: fspbkkk124

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
