server:
  port: 8888
logging:
  file: logs
   path: mylog.log
spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.222.243.64:3306/litemall
    username: root
    passwor: fspbkkk124
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*