server:
  port: 8888
logging:
  path: logs
  file:  userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.243.64:3306/litemall?serverTimeZone=GMT
    username: root
    password: fspbkkk124
mybatis:
  type-alisases-package: com.course.model
  mapper-locations:
    -mapper/*
